# Settings for libraries used by specific LAMMPS packages
# this file is auto-edited when those packages are included/excluded

PKG_INC =   -I../../lib/smd/includelink 
PKG_PATH =  
PKG_LIB =   
PKG_CPP_DEPENDS = 
PKG_LINK_DEPENDS = 

PKG_SYSINC =  $(user-smd_SYSINC) 
PKG_SYSLIB =  $(user-smd_SYSLIB) 
PKG_SYSPATH = $(user-smd_SYSPATH) 
